import re
with open('index.html', 'r', encoding='utf-8', errors='ignore') as f:
    c = f.read()
c = c.replace('Crer', 'Créer')
c = c.replace('Bibliothque', 'Bibliothèque')
c = c.replace('Sances', 'Séances')
c = c.replace('diteur', 'Éditeur')
c = c.replace('Tlcharger', 'Télécharger')
c = c.replace('Rcupr', 'Récupéré')
c = c.replace('Paramtres', 'Paramètres')
c = c.replace('chec', 'Échec')
c = c.replace('enregistr', 'enregistré')
c = c.replace('succs', 'succès')
c = c.replace('russie', 'réussie')
c = c.replace('Cr?er', 'Créer')
c = c.replace('Bibliothque', 'Bibliothèque')
c = c.replace('S?ances', 'Séances')
c = c.replace('?diteur', 'Éditeur')
c = c.replace('T?l?charger', 'Télécharger')
c = c.replace('R?cup?r?', 'Récupéré')
c = c.replace('Param?tres', 'Paramètres')
c = c.replace('CrÃ©er', 'Créer')
c = c.replace('BibliothÃ¨que', 'Bibliothèque')
c = c.replace('SÃ©ances', 'Séances')
c = c.replace('Ã‰diteur', 'Éditeur')
c = c.replace('ParamÃ¨tres', 'Paramètres')
with open('index.html', 'w', encoding='utf-8') as f:
    f.write(c)
